Traceback (most recent call last):
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tifffile import imread

image = imread('example_nuclei.tif')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mtifffile[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m imread
[0;32m----> 3[0m image [38;5;241m=[39m imread([38;5;124m'[39m[38;5;124mexample_nuclei.tif[39m[38;5;124m'[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/tifffile/tifffile.py:816[0m, in [0;36mimread[0;34m(files, aszarr, **kwargs)[0m
[1;32m    813[0m     files [38;5;241m=[39m files[[38;5;241m0[39m]
[1;32m    815[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(files, ([38;5;28mstr[39m, os[38;5;241m.[39mPathLike)) [38;5;129;01mor[39;00m [38;5;28mhasattr[39m(files, [38;5;124m'[39m[38;5;124mseek[39m[38;5;124m'[39m):
[0;32m--> 816[0m     [38;5;28;01mwith[39;00m TiffFile(files, [38;5;241m*[39m[38;5;241m*[39mkwargs_file) [38;5;28;01mas[39;00m tif:
[1;32m    817[0m         [38;5;28;01mif[39;00m aszarr:
[1;32m    818[0m             [38;5;28;01mreturn[39;00m tif[38;5;241m.[39maszarr([38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/tifffile/tifffile.py:3000[0m, in [0;36mTiffFile.__init__[0;34m(self, arg, mode, name, offset, size, _multifile, _useframes, _master, **kwargs)[0m
[1;32m   2997[0m [38;5;28;01mif[39;00m mode [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m ([38;5;28;01mNone[39;00m, [38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mr+b[39m[38;5;124m'[39m):
[1;32m   2998[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124minvalid mode [39m[38;5;132;01m{[39;00mmode[38;5;132;01m!r}[39;00m[38;5;124m'[39m)
[0;32m-> 3000[0m fh [38;5;241m=[39m FileHandle(arg, mode[38;5;241m=[39mmode, name[38;5;241m=[39mname, offset[38;5;241m=[39moffset, size[38;5;241m=[39msize)
[1;32m   3001[0m [38;5;28mself[39m[38;5;241m.[39m_fh [38;5;241m=[39m fh
[1;32m   3002[0m [38;5;28mself[39m[38;5;241m.[39m_multifile [38;5;241m=[39m [38;5;28mbool[39m(_multifile)

File [0;32m~/anaconda3/lib/python3.11/site-packages/tifffile/tifffile.py:9537[0m, in [0;36mFileHandle.__init__[0;34m(self, file, mode, name, offset, size)[0m
[1;32m   9535[0m [38;5;28mself[39m[38;5;241m.[39mis_file [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m   9536[0m [38;5;28mself[39m[38;5;241m.[39m_lock [38;5;241m=[39m NullContext()
[0;32m-> 9537[0m [38;5;28mself[39m[38;5;241m.[39mopen()

File [0;32m~/anaconda3/lib/python3.11/site-packages/tifffile/tifffile.py:9550[0m, in [0;36mFileHandle.open[0;34m(self)[0m
[1;32m   9548[0m [38;5;28mself[39m[38;5;241m.[39m_file [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mrealpath([38;5;28mself[39m[38;5;241m.[39m_file)
[1;32m   9549[0m [38;5;28mself[39m[38;5;241m.[39m_dir, [38;5;28mself[39m[38;5;241m.[39m_name [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39msplit([38;5;28mself[39m[38;5;241m.[39m_file)
[0;32m-> 9550[0m [38;5;28mself[39m[38;5;241m.[39m_fh [38;5;241m=[39m [38;5;28mopen[39m([38;5;28mself[39m[38;5;241m.[39m_file, [38;5;28mself[39m[38;5;241m.[39m_mode)
[1;32m   9551[0m [38;5;28mself[39m[38;5;241m.[39m_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m   9552[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_offset [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/ranit/Research/github/GBI-Python-2025/course_material/06182025_day3/example_nuclei.tif'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ranit/Research/github/GBI-Python-2025/course_material/06182025_day3/example_nuclei.tif'

