Traceback (most recent call last):
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tifffile import imread

image = imread('example_nuclei.tif')
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[32m/var/folders/5t/3zkcp0dd27s3txcmjn8jl96m0000gq/T/ipykernel_21167/1014929433.py[39m in [36m?[39m[34m()[39m
[32m      1[39m [38;5;28;01mfrom[39;00m tifffile [38;5;28;01mimport[39;00m imread
[32m      2[39m 
[32m----> [39m[32m3[39m image = imread([33m'example_nuclei.tif'[39m)

[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/tifffile/tifffile.py[39m in [36m?[39m[34m(files, selection, aszarr, key, series, level, squeeze, maxworkers, buffersize, mode, name, offset, size, pattern, axesorder, categories, imread, imreadargs, sort, container, chunkshape, chunkdtype, axestiled, ioworkers, chunkmode, fillvalue, zattrs, multiscales, omexml, out, out_inplace, _multifile, _useframes, **kwargs)[39m
[32m   1195[39m         ):
[32m   1196[39m             files = files[[32m0[39m]
[32m   1197[39m 
[32m   1198[39m         [38;5;28;01mif[39;00m isinstance(files, str) [38;5;28;01mor[39;00m [38;5;28;01mnot[39;00m isinstance(files, Sequence):
[32m-> [39m[32m1199[39m             with TiffFile(
[32m   1200[39m                 files,
[32m   1201[39m                 mode=mode,
[32m   1202[39m                 name=name,

[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/tifffile/tifffile.py[39m in [36m?[39m[34m(self, file, mode, name, offset, size, omexml, _multifile, _useframes, _parent, **is_flags)[39m
[32m   4230[39m                 [38;5;28;01mraise[39;00m ValueError([33m'invalid OME-XML'[39m)
[32m   4231[39m             self._omexml = omexml
[32m   4232[39m             self.is_ome = [38;5;28;01mTrue[39;00m
[32m   4233[39m 
[32m-> [39m[32m4234[39m         fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
[32m   4235[39m         self._fh = fh
[32m   4236[39m         self._multifile = [38;5;28;01mTrue[39;00m [38;5;28;01mif[39;00m _multifile [38;5;28;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m bool(_multifile)
[32m   4237[39m         self._files = {fh.name: self}

[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/tifffile/tifffile.py[39m in [36m?[39m[34m(self, file, mode, name, offset, size)[39m
[32m  13273[39m         self._offset = -[32m1[39m [38;5;28;01mif[39;00m offset [38;5;28;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m offset
[32m  13274[39m         self._size = -[32m1[39m [38;5;28;01mif[39;00m size [38;5;28;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m size
[32m  13275[39m         self._close = [38;5;28;01mTrue[39;00m
[32m  13276[39m         self._lock = NullContext()
[32m> [39m[32m13277[39m         self.open()
[32m  13278[39m         [38;5;28;01massert[39;00m self._fh [38;5;28;01mis[39;00m [38;5;28;01mnot[39;00m [38;5;28;01mNone[39;00m

[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/tifffile/tifffile.py[39m in [36m?[39m[34m(self)[39m
[32m  13292[39m             [38;5;28;01mif[39;00m self._mode [38;5;28;01mnot[39;00m [38;5;28;01min[39;00m {[33m'rb'[39m, [33m'r+b'[39m, [33m'wb'[39m, [33m'xb'[39m}:
[32m  13293[39m                 [38;5;28;01mraise[39;00m ValueError(f'invalid mode {self._mode}')
[32m  13294[39m             self._file = os.path.realpath(self._file)
[32m  13295[39m             self._dir, self._name = os.path.split(self._file)
[32m> [39m[32m13296[39m             self._fh = open(self._file, self._mode, encoding=[38;5;28;01mNone[39;00m)
[32m  13297[39m             self._close = [38;5;28;01mTrue[39;00m
[32m  13298[39m             self._offset = max([32m0[39m, self._offset)
[32m  13299[39m         [38;5;28;01melif[39;00m isinstance(self._file, FileHandle):

[31mFileNotFoundError[39m: [Errno 2] No such file or directory: '/Users/ranit/Research/github/Global-BioImaging-Image-Data-2025-Course---India/course_material/06182025_day3/example_nuclei.tif'

