Traceback (most recent call last):
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ranit/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from skimage import io, filters, restoration
from skimage.filters import sobel, gaussian, median
from skimage.morphology import disk
import matplotlib.pyplot as plt

# Load sample microscopy image
image = io.imread('https://imagej.nih.gov/ij/images/hela-cells.tif')

# Apply Gaussian filter
gaussian_filtered = gaussian(image, sigma=2)

# Apply Median filter
median_filtered = median(image, disk(3))

# Apply Sobel filter
sobel_edges = sobel(image)

# Show all results
fig, axes = plt.subplots(1, 4, figsize=(16, 5))
titles = ['Original', 'Gaussian', 'Median', 'Sobel Edges']
images = [image, gaussian_filtered, median_filtered, sobel_edges]

for ax, img, title in zip(axes, images, titles):
    ax.imshow(img, cmap='gray')
    ax.set_title(title)
    ax.axis('off')

plt.tight_layout()
plt.show()
------------------


[31m---------------------------------------------------------------------------[39m
[31mHTTPError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 7[39m
[32m      4[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[34;01m.[39;00m[34;01mpyplot[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mplt[39;00m
[32m      6[39m [38;5;66;03m# Load sample microscopy image[39;00m
[32m----> [39m[32m7[39m image = [43mio[49m[43m.[49m[43mimread[49m[43m([49m[33;43m'[39;49m[33;43mhttps://imagej.nih.gov/ij/images/hela-cells.tif[39;49m[33;43m'[39;49m[43m)[49m
[32m      9[39m [38;5;66;03m# Apply Gaussian filter[39;00m
[32m     10[39m gaussian_filtered = gaussian(image, sigma=[32m2[39m)

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/skimage/_shared/utils.py:328[39m, in [36mdeprecate_parameter.__call__.<locals>.fixed_func[39m[34m(*args, **kwargs)[39m
[32m    324[39m     [38;5;28;01melif[39;00m [38;5;28mself[39m.new_name [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m    325[39m         [38;5;66;03m# Assign old value to new one[39;00m
[32m    326[39m         kwargs[[38;5;28mself[39m.new_name] = deprecated_value
[32m--> [39m[32m328[39m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/skimage/io/_io.py:81[39m, in [36mimread[39m[34m(fname, as_gray, plugin, **plugin_args)[39m
[32m     78[39m     [38;5;28;01mif[39;00m fname.lower().endswith(([33m'[39m[33m.tiff[39m[33m'[39m, [33m'[39m[33m.tif[39m[33m'[39m)):
[32m     79[39m         plugin = [33m'[39m[33mtifffile[39m[33m'[39m
[32m---> [39m[32m81[39m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mfile_or_url_context[49m[43m([49m[43mfname[49m[43m)[49m[43m [49m[38;5;28;43;01mas[39;49;00m[43m [49m[43mfname[49m[43m,[49m[43m [49m[43m_hide_plugin_deprecation_warnings[49m[43m([49m[43m)[49m[43m:[49m
[32m     82[39m [43m    [49m[43mimg[49m[43m [49m[43m=[49m[43m [49m[43mcall_plugin[49m[43m([49m[33;43m'[39;49m[33;43mimread[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mfname[49m[43m,[49m[43m [49m[43mplugin[49m[43m=[49m[43mplugin[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mplugin_args[49m[43m)[49m
[32m     84[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(img, [33m'[39m[33mndim[39m[33m'[39m):

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/contextlib.py:141[39m, in [36m_GeneratorContextManager.__enter__[39m[34m(self)[39m
[32m    139[39m [38;5;28;01mdel[39;00m [38;5;28mself[39m.args, [38;5;28mself[39m.kwds, [38;5;28mself[39m.func
[32m    140[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m141[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mgen[49m[43m)[49m
[32m    142[39m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[32m    143[39m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([33m"[39m[33mgenerator didn[39m[33m'[39m[33mt yield[39m[33m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/site-packages/skimage/io/util.py:27[39m, in [36mfile_or_url_context[39m[34m(resource_name)[39m
[32m     25[39m [38;5;28;01mtry[39;00m:
[32m     26[39m     [38;5;28;01mwith[39;00m tempfile.NamedTemporaryFile(delete=[38;5;28;01mFalse[39;00m, suffix=ext) [38;5;28;01mas[39;00m f:
[32m---> [39m[32m27[39m         [38;5;28;01mwith[39;00m [43murllib[49m[43m.[49m[43mrequest[49m[43m.[49m[43murlopen[49m[43m([49m[43mresource_name[49m[43m)[49m [38;5;28;01mas[39;00m u:
[32m     28[39m             f.write(u.read())
[32m     29[39m     [38;5;66;03m# f must be closed before yielding[39;00m

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:189[39m, in [36murlopen[39m[34m(url, data, timeout, context)[39m
[32m    187[39m [38;5;28;01melse[39;00m:
[32m    188[39m     opener = _opener
[32m--> [39m[32m189[39m [38;5;28;01mreturn[39;00m [43mopener[49m[43m.[49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:495[39m, in [36mOpenerDirector.open[39m[34m(self, fullurl, data, timeout)[39m
[32m    493[39m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m.process_response.get(protocol, []):
[32m    494[39m     meth = [38;5;28mgetattr[39m(processor, meth_name)
[32m--> [39m[32m495[39m     response = [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[32m    497[39m [38;5;28;01mreturn[39;00m response

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:604[39m, in [36mHTTPErrorProcessor.http_response[39m[34m(self, request, response)[39m
[32m    601[39m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[32m    602[39m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[32m    603[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([32m200[39m <= code < [32m300[39m):
[32m--> [39m[32m604[39m     response = [38;5;28;43mself[39;49m[43m.[49m[43mparent[49m[43m.[49m[43merror[49m[43m([49m
[32m    605[39m [43m        [49m[33;43m'[39;49m[33;43mhttp[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[32m    607[39m [38;5;28;01mreturn[39;00m response

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:533[39m, in [36mOpenerDirector.error[39m[34m(self, proto, *args)[39m
[32m    531[39m [38;5;28;01mif[39;00m http_err:
[32m    532[39m     args = ([38;5;28mdict[39m, [33m'[39m[33mdefault[39m[33m'[39m, [33m'[39m[33mhttp_error_default[39m[33m'[39m) + orig_args
[32m--> [39m[32m533[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43m_call_chain[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:466[39m, in [36mOpenerDirector._call_chain[39m[34m(self, chain, kind, meth_name, *args)[39m
[32m    464[39m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[32m    465[39m     func = [38;5;28mgetattr[39m(handler, meth_name)
[32m--> [39m[32m466[39m     result = [43mfunc[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m
[32m    467[39m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m    468[39m         [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m~/anaconda3/envs/gbi-python-env/lib/python3.13/urllib/request.py:613[39m, in [36mHTTPDefaultErrorHandler.http_error_default[39m[34m(self, req, fp, code, msg, hdrs)[39m
[32m    612[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[32m--> [39m[32m613[39m     [38;5;28;01mraise[39;00m HTTPError(req.full_url, code, msg, hdrs, fp)

[31mHTTPError[39m: HTTP Error 404: Not Found

